name: Target Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'

    - uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
      with:
        submodules: 'recursive'

    - run: make -j$(nproc) -f target.mk
